version: '3.8'
services:
  app:
    build: . 
    ports:
      - "8000:8000" 
    environment:
      MONGODB_URI:mongodb://127.0.0.1:27017/crypto_tracker
      JWT_SECRET :"dsfhhjncvhuhejnndbbdsnncdhbbdnsbshbsd"
    depends_on:
      - redis 
    restart: always 

  redis:
    image: redis:6 
    ports:
      - "6379:6379" 
    restart: always 
